// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_bRaPkCOxwEfEnIFRZSvi-LS6vgqJfY',
    appId: '1:145019199715:web:ed9e64703fa6f99300a5d6',
    messagingSenderId: '145019199715',
    projectId: 'flutter-codelab-cupertino',
    authDomain: 'flutter-codelab-cupertino.firebaseapp.com',
    databaseURL: 'https://flutter-codelab-cupertino-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-codelab-cupertino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_lNJ_C0ip70_MLsvJ2Ftz11HSWffRxVM',
    appId: '1:145019199715:ios:44e6cc1e3e91ba5d00a5d6',
    messagingSenderId: '145019199715',
    projectId: 'flutter-codelab-cupertino',
    databaseURL: 'https://flutter-codelab-cupertino-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-codelab-cupertino.appspot.com',
    iosClientId: '145019199715-uis91vqgklq8a98knms9dmqmt87q4lbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cupertinoStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_lNJ_C0ip70_MLsvJ2Ftz11HSWffRxVM',
    appId: '1:145019199715:ios:c631e8bf4498d00d00a5d6',
    messagingSenderId: '145019199715',
    projectId: 'flutter-codelab-cupertino',
    databaseURL: 'https://flutter-codelab-cupertino-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-codelab-cupertino.appspot.com',
    iosClientId: '145019199715-4k0ajhhl6imag85p4h4e1e4a740u956p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cupertinoStore.RunnerTests',
  );
}
