// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2xVA-FV2Nqa3b2mLQzBO2AQOYNOIJ24',
    appId: '1:536911626513:web:9ea41ae9317ace3bb74cb0',
    messagingSenderId: '536911626513',
    projectId: 'flutter-codelab-74894',
    authDomain: 'flutter-codelab-74894.firebaseapp.com',
    storageBucket: 'flutter-codelab-74894.appspot.com',
    measurementId: 'G-Z3C2TDL33W',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAglaZVCxzQU6uN6HoY-2sk7RnW4WJ1Dzo',
    appId: '1:536911626513:ios:163cb4db670c0ff0b74cb0',
    messagingSenderId: '536911626513',
    projectId: 'flutter-codelab-74894',
    storageBucket: 'flutter-codelab-74894.appspot.com',
    iosClientId: '536911626513-6g9bci2b6qcce6nlv9hr0ld4i91tn80h.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdCupertinoStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAglaZVCxzQU6uN6HoY-2sk7RnW4WJ1Dzo',
    appId: '1:536911626513:ios:d5b2358971917a9eb74cb0',
    messagingSenderId: '536911626513',
    projectId: 'flutter-codelab-74894',
    storageBucket: 'flutter-codelab-74894.appspot.com',
    iosClientId: '536911626513-5vg0bnmbookj0pqal7fl8rk06iccf4fn.apps.googleusercontent.com',
    iosBundleId: 'com.storeexample.app',
  );
}

